-- Prisma migration: add missing JobOrder columns
-- Safe: uses IF NOT EXISTS so it can be applied repeatedly without error
BEGIN;

ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "jobNumber" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "productName" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "drawingRef" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "clientName" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "contactPerson" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "clientContactPerson" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "clientContactPhone" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "lpoContractNo" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "priority" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "foreman" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "workScope" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "scopeOfWorks" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "qaQcInCharge" TEXT;

ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "discount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "roundOff" DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "deletedBy" TEXT;

ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "lastEditedBy" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "lastEditedAt" TIMESTAMP(3);

-- createdAt / updatedAt defaults for new rows
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();

-- Ensure unique constraint for (jobNumber, isDeleted) exists
CREATE UNIQUE INDEX IF NOT EXISTS "JobOrder_jobNumber_isDeleted_unique" ON "JobOrder"("jobNumber", "isDeleted");

COMMIT;
