-- Prisma migration: sync schema-wide missing columns
-- Idempotent: uses IF NOT EXISTS
BEGIN;

-- Asset
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Asset" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();

-- InventoryItem
ALTER TABLE "InventoryItem" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "InventoryItem" ADD COLUMN IF NOT EXISTS "currentStock" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "InventoryItem" ADD COLUMN IF NOT EXISTS "itemName" TEXT;
ALTER TABLE "InventoryItem" ADD COLUMN IF NOT EXISTS "lastUpdated" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "InventoryItem" ADD COLUMN IF NOT EXISTS "minimumStock" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- JobOrder
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "clientContactPerson" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "clientContactPhone" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "clientName" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "contactPerson" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "deletedBy" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "drawingRef" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "jobNumber" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "lastEditedAt" TIMESTAMP(3);
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "lastEditedBy" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "lpoContractNo" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "productName" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "qaQcInCharge" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "roundOff" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "scopeOfWorks" TEXT;
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "JobOrder" ADD COLUMN IF NOT EXISTS "workScope" TEXT;

-- Ensure unique index on jobNumber + isDeleted
CREATE UNIQUE INDEX IF NOT EXISTS "JobOrder_jobNumber_isDeleted_unique" ON "JobOrder"("jobNumber", "isDeleted");

-- JobOrderItem
ALTER TABLE "JobOrderItem" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "JobOrderItem" ADD COLUMN IF NOT EXISTS "jobOrderId" TEXT;
ALTER TABLE "JobOrderItem" ADD COLUMN IF NOT EXISTS "totalPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "JobOrderItem" ADD COLUMN IF NOT EXISTS "unitPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "JobOrderItem" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "JobOrderItem" ADD COLUMN IF NOT EXISTS "workDescription" TEXT;

-- MaterialReceipt
ALTER TABLE "MaterialReceipt" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "MaterialReceipt" ADD COLUMN IF NOT EXISTS "purchaseOrderItemId" TEXT;
ALTER TABLE "MaterialReceipt" ADD COLUMN IF NOT EXISTS "qualityStatus" TEXT;
ALTER TABLE "MaterialReceipt" ADD COLUMN IF NOT EXISTS "receivedBy" TEXT;
ALTER TABLE "MaterialReceipt" ADD COLUMN IF NOT EXISTS "receivedDate" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "MaterialReceipt" ADD COLUMN IF NOT EXISTS "receivedQuantity" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MaterialReceipt" ADD COLUMN IF NOT EXISTS "storageLocation" TEXT;

-- MaterialRequest
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "assetId" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "deletedBy" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "itemName" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "jobOrderId" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "lastEditedAt" TIMESTAMP(3);
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "lastEditedBy" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "materialType" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "preferredSupplier" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "reasonForRequest" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "requestContext" TEXT NOT NULL DEFAULT 'JOB_ORDER';
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "requestedAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "requestedBy" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "requestNumber" TEXT;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "requiredDate" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "stockQtyInInventory" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "MaterialRequest" ADD COLUMN IF NOT EXISTS "urgencyLevel" TEXT NOT NULL DEFAULT 'NORMAL';

-- MaterialRequestItem
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "deletedBy" TEXT;
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "inventoryItemId" TEXT;
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "itemName" TEXT;
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "materialRequestId" TEXT;
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "preferredSupplier" TEXT;
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "reasonForRequest" TEXT;
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "requiredDate" TIMESTAMP(3);
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "stockQtyInInventory" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "MaterialRequestItem" ADD COLUMN IF NOT EXISTS "urgencyLevel" TEXT NOT NULL DEFAULT 'NORMAL';

-- ProcurementAction
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "actionBy" TEXT;
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "actionDate" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "actionType" TEXT;
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "deletedBy" TEXT;
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "expectedDelivery" TIMESTAMP(3);
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "lastEditedAt" TIMESTAMP(3);
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "lastEditedBy" TEXT;
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "materialRequestId" TEXT;
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "quotationAmount" DOUBLE PRECISION;
ALTER TABLE "ProcurementAction" ADD COLUMN IF NOT EXISTS "supplierName" TEXT;

-- PurchaseOrder
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "actualDelivery" TIMESTAMP(3);
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "createdBy" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "expectedDelivery" TIMESTAMP(3);
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "orderDate" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "poNumber" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "supplierContact" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "supplierName" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "totalAmount" DOUBLE PRECISION;
ALTER TABLE "PurchaseOrder" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();

-- PurchaseOrderItem
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "deliveryStatus" TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "materialRequestId" TEXT;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "orderedQuantity" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "purchaseOrderId" TEXT;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "receivedQuantity" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "totalPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "unitPrice" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "PurchaseOrderItem" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();

-- StatusHistory
ALTER TABLE "StatusHistory" ADD COLUMN IF NOT EXISTS "changedAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "StatusHistory" ADD COLUMN IF NOT EXISTS "changedBy" TEXT;
ALTER TABLE "StatusHistory" ADD COLUMN IF NOT EXISTS "materialRequestId" TEXT;
ALTER TABLE "StatusHistory" ADD COLUMN IF NOT EXISTS "newStatus" TEXT;
ALTER TABLE "StatusHistory" ADD COLUMN IF NOT EXISTS "oldStatus" TEXT;

-- Supplier
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "contactPerson" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "defaultCurrency" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "leadTimeDays" INTEGER;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "paymentTerms" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "preferred" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "taxId" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "tradeLicense" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "tradingName" TEXT;
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "Supplier" ADD COLUMN IF NOT EXISTS "website" TEXT;

-- User
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "approvedBy" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT now();
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hashedPassword" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "joiningDate" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT now();

COMMIT;
